import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <main className={styles.main}>
          <Link href="/my-page">
            <a>Go to my page (middleware called)</a>
          </Link>

          <Link href="/my-page?hello=world">
            <a>Go to my page with params (middleware not called)</a>
          </Link>
        </main>
      </main>
    </div>
  )
}
